### ISSUE TITLE
graylog2ctl script missing from Ubuntu package?

### ISSUE THREAD

**Issue by victorhooi** [Graylog2/fpm-recipes#26]
I've just installed the graylog2-server package from the repository, and I cannot seem to find the `graylog2ctl` script referenced in the docs (https://www.graylog2.org/resources/documentation/setup/server).

This is what the package installed:

```
$ dpkg -L graylog2-server
/.
/usr
/usr/share
/usr/share/graylog2-server
/usr/share/graylog2-server/bin
/usr/share/graylog2-server/bin/graylog2-es-timestamp-fixup
/usr/share/graylog2-server/plugin
/usr/share/graylog2-server/graylog2-server.jar
/etc
/etc/default
/etc/default/graylog2-server
/etc/graylog2.conf
/etc/init
/etc/init/graylog2-server.conf
/etc/graylog2
/etc/graylog2/server
/etc/graylog2/server/log4j.xml
```

And there doesn't seem to be a service file installed either, so I'm not sure of the cleanest way to start graylog2 either.

**Comment by bernd** [comment]
The graylog2ctl is not included in the packages because there are startup scripts to handle starting and stopping of Graylog. On Ubuntu we install upstart scripts into the `/etc/init/` directory.

You can start the server with `start graylog2-server` and stop it with `stop graylog2-server`.

The packages are tested and supported on the Ubuntu LTS releases 12.04 and 14.04.
