### ISSUE TITLE
RPMs and Java 7, 8

### ISSUE THREAD

**Issue by valerioj** [Graylog2/fpm-recipes#34]
Hello. I'm using the Puppet modules to automatically install Graylog, and I found out that the Graylog packages require "java >= 1:1.7.0".

The problem is that java-1.8.0-openjdk provides "java = 1.8.0", i.e. they dropped the epoch notation "1:" in this version.

The result is that the RPMs will ask for version 1.7 even if version 8 is installed.

An alternative could be that the RPM requires jre >= 1.7.0 instead of java, which has the same notation for both versions (1.7.0 and 1.8.0 respectively).

Would it be possible to change that? Do you think of other alternatives?

Thanks in advance.

**Comment by peteGS** [comment]
This issue also affects our install on CentOS 6 using the Graylog RPM's.

I have found our ElasticSearch much improved with Java 8 rather than Java 7 and the ElasticSearch RPM's have no Java dependencies which makes it very easy.

I would suggest that the Java dependency simply be removed from the Graylog RPM's in the same manner as that will give users the most flexibility as to which version they should use.

Cheers Pete

**Comment by bernd** [comment]
Thank you for the report. I guess I will just remove the dependency.

- [ ] Remove Java dependency from packages.
- [ ] Adjust documentation.

**Comment by valerioj** [comment]
Thank you. This solution would work for me. Let me know when the RPMs are updated.

**Comment by peteGS** [comment]
Thanks very much! And thanks also for your efforts in providing the packages too. It is very much appreciated.

**Comment by bernd** [comment]
I am adding the java dependencies back as "recommends" for Debian packages to avoid Java uninstall by apt on update from 1.0.

**Comment by bernd** [comment]
@valerioj The Graylog 1.1 packages do not have the Java dependency anymore. Please let us know if you still run into problems.
