### ISSUE TITLE
Ubuntu Install doesn't install graylog-web

### ISSUE THREAD

**Issue by itprosusa** [Graylog2/fpm-recipes#62]
Your instructions for install using Ubuntu packages apt-get doesn't ever reference installing graylog-web.  The web server doesn't respond and there is not /etc/graylog/web folder if I try to run apt-get install graylog-web it says thats referenced but does not exist.  Readying old walkthroughs it seems like it should exist.

**Comment by edmundoa** [comment]
Hi,

The web interface is a single page application, that gets served from the server since 2.0. Therefore there are no packages for it. Please use our (documentation page)[http://docs.graylog.org/en/2.0/pages/configuring_webif.html] instead of old guides, as those will not probably work.

Please post any questions on this to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog). We use GitHub issues for tracking bugs in Graylog itself, but this isn't one.

Thank you!
