### ISSUE TITLE
Package graylog-web is not available (Ubuntu 14.04 x64)

### ISSUE THREAD

**Issue by schlos** [Graylog2/fpm-recipes#63]
Following steps in docs:
http://docs.graylog.org/en/2.0/pages/installation/operating_system_packages.html

> $ sudo apt-get install apt-transport-https
> $ wget https://packages.graylog2.org/repo/packages/graylog-2.0-repository_latest.deb
> $ sudo dpkg -i graylog-2.0-repository_latest.deb
> $ sudo apt-get update
> $ sudo apt-get install graylog-server

Also I've uncommented and set in /etc/graylog/server/server.conf:
```
web_enable = true
web_listen_uri = http://127.0.0.1:9000/
rest_transport_uri = http://127.0.0.1:12900/
```

Testing web fails:
```
# wget http://127.0.0.1:9000/
--2016-05-08 12:22:47--  http://127.0.0.1:9000/
Connecting to 127.0.0.1:9000... failed: Connection refused.
```

And I found some older guides to install graylog-web, but fails (same as #56):
```
# sudo apt-get install graylog-web
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package graylog-web is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'graylog-web' has no installation candidate
```

Is package graylog-web been dropped? Or renamed?
I'd appreciate guide how to install graylog web interface for 2.0.0. (to work with graylog server v2.0.0.).

Thanks!

**Comment by jalogisch** [comment]
Dear @schlos 

in the Documents you are able to find this part: http://docs.graylog.org/en/2.0/pages/configuring_webif.html

Please do not mix up guides from Version prior 2.0.0 because the Web Interface is now part of Graylog Server (for your reference: https://www.graylog.org/blog/55-announcing-graylog-v2-0-ga ).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
